In [1]:
import numpy as np

In [2]:
np.array([2,3,4,5,6])

array([2, 3, 4, 5, 6])

In [3]:
type(np.array([2,3,4,5,6]))

numpy.ndarray

In [4]:
np.array([[2,3,4], [4,5,6]])

array([[2, 3, 4],
       [4, 5, 6]])

In [5]:
np.array([[2,3,4], [4,5,6]])

numpy.ndarray

In [6]:
np.array([[1,2,3,4],[2,3,4,5]])

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [7]:
l = [[1,2,3,4],[2,3,4,5]]

In [8]:
l[0]

[1, 2, 3, 4]

In [9]:
l[0][1]

2

In [10]:
a = np.array([3,4,5,6], ndmin = 5)

In [11]:
a

array([[[[[3, 4, 5, 6]]]]])

In [13]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [14]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
arr.ndim

2

In [18]:
np.random.randint(1,10,(4,4))

array([[6, 7, 7, 6],
       [9, 3, 5, 9],
       [3, 6, 7, 3],
       [5, 8, 9, 3]])

In [19]:
np.random.randint(1,10,(4,4,2))

array([[[1, 7],
        [7, 1],
        [6, 9],
        [9, 6]],

       [[6, 1],
        [4, 7],
        [2, 8],
        [2, 1]],

       [[9, 8],
        [3, 8],
        [1, 7],
        [8, 7]],

       [[5, 3],
        [7, 8],
        [1, 4],
        [1, 5]]])